Repository pmndrs/react-three-fiber, pull requests merged in 2021-03, with the labels that each got.

#1044 Updates Lines example after Three.geometry deprecation
  examples/src/demos/dev/Lines.js
Labels: documentation

#1104 [v6] prop-defaults
  example/src/App.tsx
  packages/fiber/src/core/renderer.ts
Labels: v6

#1107 Fix: ColorProps type
  example/src/demos/ResetProps.tsx
  packages/fiber/src/three-types.ts
Labels: needs more info, v6
